Add draft holiday cancellation guide
carpentries/trainers pull request #115
Opened 2021-05-27 19:24 UTC by jcoliver

A draft of practice to use for cancelling trainers meeting for discussion at June Trainers leadership meeting (addresses #93 ).

Going to add everyone as a reviewer, although not sure that's the right mechanism for adopting this thing. :thinking:

2021-05-27 19:30 UTC, brownsarahm commented
A challenge with 24h notice is that a trainer could be relying on the meeting for a pre-workshop discussion; what could we do to support people in that?

2021-05-28 17:49 UTC, karenword commented
Thanks @jcoliver ! Per Sarah's comment, I think these last minute changes are a little hard on everyone and it would be nice to plan in advance, though of course we should always leave room for last minute changes. I also wonder how Trainers are going to let me know. Maybe I can set up a request form and bump it a couple of times a year, with a list of upcoming meeting dates to object to? And if something still comes up at the last minute, they can use the form so that those holidays can be planned for in the future?

2021-05-28 22:17 UTC, Denubis commented
Question: Since nationalities and holidays are public data (and I'm reminded of the good Friday cancellation a few months ago that the Aussies went 'but it's a holiday!' -- isn't it easier to use nationalities from github, apply the "holiday template" to the meetings calendar and go from there? Adding another response required for known information sounds a bit tedious to me.

2021-05-31 15:55 UTC, karenword commented
It is possible that we could determine nationality for all Trainers and use official public holidays -- this indeed would have addressed the most recent problem. However, there may be widely celebrated religious holidays that are not state holidays, for example. Also, as our community expands, it may not be practical to cancel meetings for *every* state holiday in *every* country where we have a Trainer. I think this calls for one of those fuzzy middle points, which is a good reason to create a policy (and change it as needed).

2021-06-01 02:00 UTC, marklcrowe commented on policy/holiday-scheduling-process.md
> ++ Notification of such a cancellation should be made at least 24 hours before the
```suggestion
+ Notification of such a cancellation should be made at least 72 hours before the
```

2021-06-01 02:01 UTC, marklcrowe requested changes
This discussion seems to be getting a bit involved. Isn't the ideal for this request basically "when should we cancel a trainer meeting and how much notice is required" rather than developing complex systems for identifying public holidays and the like. 

I'm in favour of the initial suggestion - that the community itself is responsible for flagging any significant clashes. And this doesn't in itself mean that a meeting is cancelled, especially if someone is relying on it for a pre-workshop meeting (do people register that beforehand so we'd know?); that again is covered in the proposal, it being at the discretion of the Director of Training. Neither of those really should be a last minute thing so I'd prefer that the notice period was a bit longer, ideally 72h (48 would be OK).

tl;dr - I approve this proposal if we extend the cancellation time out to 72h

2021-06-02 00:23 UTC, arinbasu commented on policy/holiday-scheduling-process.md
> ++ Notification of such a cancellation should be made at least 24 hours before the
I think a 24 hour notice is too early, perhaps a 72 hour window is better

2021-06-02 00:23 UTC, arinbasu submitted a review, later dismissed

2021-06-11 21:11 UTC, jcoliver commented
The draft policy is explicit in responsibility, but vague in conditions _why_ a meeting may be cancelled. The legion of holidays our trainer community experiences is diverse, and while we might be able to track holidays, cancellation because of a holiday should only happen when that holiday would influence a significant* portion of the Trainers community that would otherwise attend a Trainers meeting (i.e. even if National Doughnut Day (either of them) were to fall on a Trainers meeting day, it remains an open question of how many Trainers would skip the Trainers meeting to celebrate the glory of leavened fried dough).

To address questions of how cancellation might effect pre-training discussions, we could add a line to the effect of "The Director of Instructor Training should attempt to accommodate meetings when novice instructors (< 1year) have signed up for pre-workshop discussions"

*Recognizing, of course, that "significant" is arbitrary.

2021-06-18 17:29 UTC, brownsarahm commented on policy/holiday-scheduling-process.md
> +responsibility of the Carpentries' Director of Instructor Training.
```suggestion
+ The decision to cancel a regularly scheduled trainers meeting will be at the 
discretion of the Carpentries' Director of Instructor Training or a designated proxy. 
```

proxy meaning like, if the director was out of office for some reason another person could cancel per whatever  arrangement for coverage was made by the director

2021-06-18 17:29 UTC, brownsarahm commented on policy/holiday-scheduling-process.md
> +scheduled meeting time.
```suggestion
scheduled meeting time through all normal meeting announcement communication channels. 
```

2021-06-18 17:31 UTC, brownsarahm commented on policy/holiday-scheduling-process.md
> +regularly scheduled trainer meetings.
```suggestion
+ Any member of the Carpentries Trainers community may notify the 
Director of Instructor Training of significant holidays that conflict with 
regularly scheduled trainer meetings. 
```
also maybe, logically this bullet should be first?

2021-06-18 17:37 UTC, brownsarahm commented
I also like @jcoliver 's suggestion about new trainer pre/post workshops.  

Maybe we say that new discussion topics can be postponed at the shorter (72h) notice, but that canceling time for pre/post discussions has to be done further in advance maybe by the preceding meeting?  For holidays where there's no one to facilitate level impact it's feasible that the director can update the calendar a few months in advance.  For things that impact fewer people, but still enough that we want to postpone important discussions in favor of greater inclusion the short notice should be okay.

2021-06-18 20:03 UTC, jcoliver commented on policy/holiday-scheduling-process.md
> ++ Notification of such a cancellation should be made at least 24 hours before the
Indeed. Updated to 72 hours.

2021-07-12 13:26 UTC, ACharbonneau approved these changes

2021-07-12 23:43 UTC, jcoliver commented
@jcoliver, FLTOG, add that piece about accommodating pre/post June 11: "The Director of Instructor Training should attempt to accommodate meetings when novice instructors (< 1year) have signed up for pre-workshop discussions"

2021-07-16 14:25 UTC, ACharbonneau approved these changes

2021-07-19 16:35 UTC, brownsarahm commented on policy/holiday-scheduling-process.md
> +when novice instructors (< 1year) have signed up for pre-workshop discussions
```suggestion
when novice trainers (< 1year) have signed up for pre-workshop discussions
```

2021-07-19 18:29 UTC, jcoliver commented
Thanks for the feedback, folks. @marklcrowe , I think this needs your stamp of approval to move forward.

2021-07-19 19:24 UTC, brownsarahm approved these changes

2021-07-19 23:05 UTC, marklcrowe approved these changes

2021-07-19 23:10 UTC, merged