Add Trainer Community meeting schedule to README
carpentries/trainers pull request #155
Opened 2022-01-19 20:10 UTC by karenword

Per discussion at Trainers Leadership meeting Feb 17, 2022. Also includes instructions to submit proposal via Discussions and suggest cancellations via Issues, with email alternatives.

Please double check my link formatting shortcuts? :)

2022-01-19 21:29 UTC, brownsarahm requested changes
the discussion/issue links look for files with those names, not the appropriate sections, i htink we hav eto use full url

2022-01-19 21:29 UTC, brownsarahm commented on README.md
> +To submit a proposal here, please visit the [Discussions tab](discussions) and
```suggestion
To submit a suggest a meeting topic here, please visit the [Discussions tab](discussions) and 
```
to differentiate from other use of proposals on this repo

2022-01-19 21:29 UTC, brownsarahm commented on README.md
> +To submit a proposal here, please visit the [Discussions tab](discussions) and
this link doesn't work

2022-01-19 23:11 UTC, marklcrowe commented
> Per discussion at Trainers Leadership meeting Feb 17, 2022. 

Karen, did you mean Jan 17, 2022?

2022-01-19 23:45 UTC, jcoliver submitted a review, later dismissed

2022-01-20 00:39 UTC, brownsarahm submitted a review, later dismissed

2022-01-20 16:52 UTC, JCSzamosi commented
Looking at the meeting dates, I would just like to flag March 17, which is Purim. It's not as serious a holiday as something like Yom Kippur, but many Jews do treat it as a day of rest, so if we can avoid having a meeting on that day it might be better.

2022-02-07 18:45 UTC, brownsarahm approved these changes

2022-02-15 00:42 UTC, merged