link to list of current trainers
carpentries/trainers pull request #205
Opened 2022-07-15 16:16 UTC by brownsarahm

closes #204

2022-07-18 15:20 UTC, klbarnes20 commented
Thanks @brownsarahm!

2022-07-18 22:07 UTC, marklcrowe commented on governance.md
> +* Five (5) voting members, listed on the [README of the trainers repo](README)
Should the link be to README.md ?

2022-07-18 22:08 UTC, marklcrowe requested changes
Should the link be to README.md rather than just README?

2022-07-21 23:14 UTC, jcoliver approved these changes

2022-07-21 23:26 UTC, marklcrowe approved these changes

2022-07-21 23:45 UTC, merged