Add draft of 2022-09-08 leadership meeting minutes
carpentries/trainers pull request #215
Opened 2022-09-14 19:05 UTC by jcoliver

Minutes from 2022-09-08 Trainers Leadership Committee meeting.

2022-09-19 04:01 UTC, marklcrowe commented on leadership_minutes/2022-09-08-leadership-minutes.md
> +4. Low feedback scores from an event: thinking about follow-up
Hi @jcoliver, this item (low feedback scores) was added to the agenda in the wrong place - it's supposed to be one of the core team update items. Please can you move it to that section and update numbering accordingly? Sorry for not editing that on the agenda notes at the time.

2022-09-19 04:04 UTC, marklcrowe requested changes
So according to GitHub, my comment below (line 71-73, item 4) isn't actually a comment, and I need to leave a comment requesting changes. So copy-paste as below:

Hi @jcoliver, this item (low feedback scores) was added to the agenda in the wrong place - it's supposed to be one of the core team update items. Please can you move it to that section and update numbering accordingly? Sorry for not editing that on the agenda notes at the time.

2022-09-19 12:08 UTC, paocorrales approved these changes

2022-09-19 18:07 UTC, bonnyad approved these changes

2022-09-19 18:09 UTC, bonnyad submitted a review, later dismissed

2022-09-20 01:55 UTC, marklcrowe submitted a review, later dismissed
Thanks for making that correction Jeff

2022-09-20 11:16 UTC, brownsarahm commented on leadership_minutes/2022-09-08-leadership-minutes.md
> +        - Sarah, and Pao agree to not recording
```suggestion
        - Sarah, and Pao agree to not sharing recording
```

2022-09-20 11:19 UTC, brownsarahm commented on leadership_minutes/2022-09-08-leadership-minutes.md
> +        - Sarah, and Pao agree to not recording
@paocorrales is that what you remember agreeing to? If so, can you commit that? then I'll also approve the minutes

2022-09-20 13:31 UTC, paocorrales commented on leadership_minutes/2022-09-08-leadership-minutes.md
> +        - Sarah, and Pao agree to not recording
Yes, I meant not sharing the recording.

2022-09-20 13:32 UTC, paocorrales approved these changes

2022-09-20 19:57 UTC, brownsarahm approved these changes

2022-09-26 20:52 UTC, merged