Update README.md for 2023
carpentries/trainers pull request #242
Opened 2023-03-17 21:45 UTC by karenword

Leadership and meeting dates

2023-03-17 23:21 UTC, karenword commented
addresses #238

2023-03-20 03:34 UTC, marklcrowe commented on README.md
>  Elected members of the Trainers Leadership Committee as of March, 2022 are:
March 2023

2023-03-20 03:45 UTC, marklcrowe requested changes

2023-03-20 03:45 UTC, marklcrowe commented on README.md
>  Elected members of the Trainers Leadership Committee as of March, 2022 are:
Should be March 2023

2023-03-20 03:45 UTC, marklcrowe commented on README.md
> +Apr 7 (Primary) - pre/post discussion
Karen, which timezone are these dates in? They are all Fridays, which corresponds to Saturday morning Aus/NZ. Last year they were Thursdays. (/Friday am). Should they all be made one day earlier?

7th April is also Easter weekend, so even it it's Thursday for you, it will be Good Friday here. We don't necessarily need to cancel/change the date, but there are unlikely to be any Aus/NZ attendees.

2023-03-21 18:32 UTC, karenword commented on README.md
> +Apr 7 (Primary) - pre/post discussion
whoops, great catch! We'll discuss holiday cancellations at the meeting. In the past we have erred on the side of not cancelling because observing all global holidays is taxing and observing only some of them is hard to choose fairly (though we sometimes have to observe holidays that subtract supporting Core Team members)

2023-03-21 23:44 UTC, paocorrales reviewed
Add roles

2023-03-21 23:44 UTC, paocorrales commented on README.md
> +- Mark Crowe
```suggestion
- Mark Crowe (chair)
```

2023-03-21 23:44 UTC, paocorrales commented on README.md
> +- Nathaniel Porter
```suggestion
- Nathaniel Porter (secretary)
```

2023-03-27 06:30 UTC, marklcrowe approved these changes

2023-03-27 14:11 UTC, ndporter approved these changes

2023-04-15 15:44 UTC, merged