Add June 2023 minutes
carpentries/trainers pull request #258
Opened 2023-06-21 17:05 UTC by ndporter

2023-06-21 17:42 UTC, karenword commented on leadership_minutes/2023-06-20-leadership-minutes.md
> +        - Community List
```suggestion
        - Community List
        - Not possible to systematically contact or point to local community leaders (per request at Trainer meeting) because we do not have a formal role or list for that currently.
```
I'd like to recognize that Liz's request was discussed, at least, even though we are unable to implement

2023-08-03 22:28 UTC, marklcrowe requested changes

2023-08-03 22:30 UTC, marklcrowe commented
Hi Nathaniel, if you could make my proposed change from ‘7/24’ to ‘24 July’ I’d be happy to approve it. Numerical format for dates isn’t ideal for an international organisation with different formatting conventions.

[Update] Just realised that I might have added this as a comment rather than a change request – I think I’ve fixed that now.

Cheers

Mark

--
Mark Crowe
Skills Development Manager
[QCIF Skills Development logo]<https://www.qcif.edu.au/services/skills-development/>[ResBazQld 2023 logo]<https://resbaz.github.io/resbaz2023qld/>

Queensland Cyber Infrastructure Foundation Ltd (QCIF)<http://qcif.edu.au/>
***@***.******@***.***> | 0434 331588
www.qcif.edu.au<http://www.qcif.edu.au> | [signature_2237584107]  @qcifltd<https://twitter.com/qcifltd> @marklcrowe<https://twitter.com/marklcrowe> | [signature_2092932782]  @qcif<https://www.linkedin.com/company/1664945>

From: Nathaniel D Porter ***@***.***>
Date: Friday, 4 August 2023 at 01:44
To: carpentries/trainers ***@***.***>
Cc: Mark Crowe ***@***.***>, Comment ***@***.***>
Subject: Re: [carpentries/trainers] Add June 2023 minutes (PR #258)

@carpentries/trainers-leadership<https://github.com/orgs/carpentries/teams/trainers-leadership> we still need an approving review to merge this.

—
Reply to this email directly, view it on GitHub<https://github.com/carpentries/trainers/pull/258#issuecomment-1664222399>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMEBKDC6E23RLFJUTY4ZAPDXTPBOFANCNFSM6AAAAAAZPBNPSA>.
You are receiving this because you commented.Message ID: ***@***.***>

2023-08-04 14:55 UTC, ndporter commented on leadership_minutes/2023-06-20-leadership-minutes.md
> +  - Checkout project implementation scheduled for 7/24
Should be better now

2023-08-07 01:46 UTC, marklcrowe approved these changes

2023-08-07 01:47 UTC, merged