add draft trainers meeting guide
carpentries/trainers pull request #310
Opened 2024-12-11 18:34 UTC by jonathanwheeler01

To replace the current outline in the policy directory.

2024-12-11 21:01 UTC, ndporter requested changes
In addition to the specific suggestions and questions in the line by line review, the draft guide should be updated to ensure consistent use of list types (e.g.  don't switch between numbered and bulleted lists in the middle of a section).

2025-03-15 00:40 UTC, sheraaronhurt commented on policy/trainers_meeting_guide.md
> +    2. Add attendance to the Core Team's spreadsheet.
no, this can remain a CT item

2025-03-15 00:42 UTC, sheraaronhurt commented
We don't discuss the timeline for when to cancel the 2nd meeting. We should add something about that: 
- when to send email
- remove from the community calendar

2025-05-29 20:42 UTC, jonathanwheeler01 commented on policy/trainers_meeting_guide.md
> +        - A "topic of the month."
We have been having topics of the month at each meeting - I suppose that makes it a meeting topic. I will edit.

2025-06-17 22:49 UTC, somet-code requested changes
Besides my comments, there are some spacing inconsistencies, but I think everything renders fine.

2025-06-17 22:49 UTC, somet-code commented on policy/trainers_meeting_guide.md
> +- **Responsibility**: The Instructor Trainers Leadership Committee (TLC).
ITLC instead of TLC for consistency

2025-06-17 22:49 UTC, somet-code commented on policy/trainers_meeting_guide.md
> +    2. Encourage members to propose topics in the [trainers etherpad](https://pad.carpentries.org/trainers) under the "Propose a Topic" section.
Capitalize Trainers for consistency

2025-06-17 22:49 UTC, somet-code commented on policy/trainers_meeting_guide.md
> +**Before sending email, prepare Etherpad using template text at the bottom of the page. This will generate the time-date links to replace those in the email template below.**
Etherpad is capitalized here but not elsewhere. I'm not sure what is preferred.

2025-06-17 22:49 UTC, somet-code commented on policy/trainers_meeting_guide.md
> +    3. Announce schedules and ensure they are added to the community calendars. Remind Instructor Trainers every October 1 about re-importing calendar items to accommodate daylight savings changes.
Would the sentence about the October 1 reminder work better as a sub bullet point, or a separate bullet point?

Also, I recommend changing daylight savings to Daylight Saving Time.

2025-06-17 22:49 UTC, somet-code commented on policy/trainers_meeting_guide.md
> +### Meeting reminder Template:
It seems either reminder should be capitalized or template should be lowercase.

2025-06-17 22:49 UTC, somet-code commented on policy/trainers_meeting_guide.md
> +### Meeting cancellation Template:
It seems either cancellation should be capitalized or template should be lowercase.

2025-06-30 15:30 UTC, sheraaronhurt approved these changes

2025-06-30 17:22 UTC, jessesadler approved these changes

2025-06-30 17:26 UTC, merged