Add draft of 2021-03-29 leadership meeting minutes
carpentries/trainers pull request #94
Opened 2021-04-01 19:08 UTC by jcoliver

Draft of the minutes for public consumption for the 2021-03-29 UTC leadership meeting.

2021-04-02 00:02 UTC, brownsarahm requested changes
I want to update the discussion on the project items

2021-04-02 00:02 UTC, brownsarahm commented on leadership_minutes/2021-03-29-leadership-minutes.md
> +    - checkout and piloting
```suggestion
6. ~5~ Projects, Content: delegate here (Sarah, 15min)
    - Sarah: per above decision I will create proposals about doing each of these ideas and we'll delegate tasks at the next meeting
```

2021-04-02 00:02 UTC, brownsarahm commented on leadership_minutes/2021-03-29-leadership-minutes.md
> +    - Arin: +1
```suggestion
    - Arin: +1
    - Sarah: ok, we will proceed with small proposals for project ideas that then we can move into full proposals after. 
```

2021-04-02 20:55 UTC, jcoliver commented
I somehow managed to remove @marklcrowe from Reviewers list when requesting re-review and now I cannot, for the life of me, figure out how to add him back to the list of Reviewers. I don't even think I can @ properly... :raised_eyebrow:

2021-04-02 21:22 UTC, karenword commented
Neither can I... @maneesha any thoughts on why we can't request review from someone who has accepted maintainer status in this repo?

2021-04-05 12:02 UTC, maneesha commented
@marklcrowe  was removed as an individual maintainer and added to the team.  @jcoliver  may have tried to tag him in that in-between switch over time.  Mark has been added as a reviewer to this issue.

2021-04-05 14:01 UTC, ACharbonneau approved these changes

2021-04-05 14:41 UTC, brownsarahm approved these changes

2021-04-08 07:47 UTC, marklcrowe commented
Hi all, sorry for being a bit unresponsive about this - I've had a bit of
time off over Easter, and also must admit that I'm struggling with git. I'm
not sure what I'm supposed to do as a reviewer or what I would need to do
if I had any corrections to suggest (not that I do on this occasion). Can
someone give me some pointers please? I'm also not sure of the relationship
between the trainers-leadership section and the trainers repository - are
these minutes already public to the full trainer community? Not that's an
issue, but I just wanted to understand whether the minutes are semi-public
even in their draft format.

Also in following up the story of my being the recipient of accidental
removal and intentional reinstatement, I discovered that the Trainers
Leadership team is currently missing Arin but contains Christina K. I don't
know Christina, but should she be part of this group? And presumably we
should include Arin - what happened to him along the way?

Cheers

Mark


On Fri, Apr 2, 2021 at 5:09 AM Jeff Oliver ***@***.***> wrote:

> @jcoliver <https://github.com/jcoliver> requested your review on: #94
> <https://github.com/carpentries/trainers/pull/94> Add draft of 2021-03-29
> leadership meeting minutes.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/carpentries/trainers/pull/94#event-4542949370>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMEBKDFPULXB6GTCK4PL5F3TGTAFJANCNFSM42HUN43A>
> .
>

2021-04-08 14:51 UTC, brownsarahm commented
@maneesha Can you confirm that Arin has been invited, but not accepted?  and can you remove Christina?

2021-04-12 23:36 UTC, marklcrowe approved these changes

2021-05-12 20:29 UTC, arinbasu approved these changes

2021-05-13 19:03 UTC, merged